[package]
name = "rqs_lib"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
aes = "0.9"
anyhow.workspace = true
axum = { version = "0.8", default-features = false, features = ["http1", "tokio", "json", "query"] }
axum-server = { version = "0.8.0", features = ["tls-rustls-no-provider"] }
base64 = "0.23"
bluer = { version = "0.17", features = ["bluetoothd"] }
bytes = "1.12"
cbc = { version = "0.2", features = ["alloc"] }
directories = "6"
futures = "0.3"
gethostname = "1.1.0"
hkdf = "0.13"
hmac = "0.13"
if-addrs = "0.15"
log.workspace = true
mdns-sd = "0.21"
mime_guess = "2"
p256 = { version = "0.14", features = ["ecdh", "getrandom"] }
prost = "0.14"
rand = "0.10"
rcgen = "0.14.10"
reqwest = { version = "0.13", default-features = false, features = ["rustls-no-provider", "json", "stream", "http2", "query"] }
rustls = { version = "0.23.45", default-features = false, features = ["ring", "std", "tls12", "logging"] }
serde.workspace = true
serde_json = "1.0.151"
sha2 = "0.11"
socket2 = "0.6.5"
tokio.workspace = true
tokio-rustls = { version = "0.26", default-features = false }
tokio-util = { workspace = true, features = ["codec", "io"] }
tower-layer = "0.3"
ts-rs = { version = "12", features = ["serde-compat"] }

[build-dependencies]
prost-build = "0.14"
