[package]
name = "rqs_lib"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
aes = "0.9"
anyhow.workspace = true
base64 = "0.23"
bluer = { version = "0.17", features = ["bluetoothd"] }
bytes = "1.12"
cbc = { version = "0.2", features = ["alloc"] }
directories = "6"
futures = "0.3"
gethostname = "1.1.0"
hkdf = "0.13"
hmac = "0.13"
if-addrs = "0.15"
log.workspace = true
mdns-sd = "0.21"
mime_guess = "2"
p256 = { version = "0.14", features = ["ecdh", "getrandom"] }
prost = "0.14"
rand = "0.10"
serde.workspace = true
sha2 = "0.11"
tokio.workspace = true
tokio-util = { workspace = true, features = ["codec"] }
ts-rs = { version = "12", features = ["serde-compat"] }

[build-dependencies]
prost-build = "0.14"
