[package]
name = "rquickshare"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
default-run = "rquickshare"

[build-dependencies]
tauri-build = { version = "2.6", features = [] }

[dependencies]
anyhow.workspace = true
arboard = { version = "3", default-features = false, features = ["wayland-data-control"] }
clap = { version = "4.6.7", features = ["derive"] }
fern = { version = "0.7", features = ["colored"] }
futures-util = "0.3.34"
humantime = "2"
ksni = "0.3"
libc = "0.2.189"
log.workspace = true
notify-rust = "4.18"
rqs_lib = { path = "../../../core_lib" }
serde.workspace = true
serde_json = "1"
tauri = { version = "2.11", features = ["image-png"] }
tauri-plugin-autostart = "2.5"
tauri-plugin-clipboard-manager = "2.3"
tauri-plugin-dialog = "2.7"
tauri-plugin-opener = "2.5"
tauri-plugin-single-instance = "2.4"
tauri-plugin-store = "2.4"
tokio.workspace = true
zbus = { version = "5", default-features = false, features = ["tokio"] }
