// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The protocol a nearby device is reached over.
 */
export type Protocol = "QuickShare" | { "LocalSend": { https: boolean, } };
