// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceType } from "./DeviceType";

export type RemoteDeviceInfo = { name: string, device_type: DeviceType, 
/**
 * For a LocalSend sender, the fingerprint of the certificate it proved
 * it holds. Names can be anything, so LocalSend devices are trusted by
 * this instead.
 */
fingerprint: string | null, };
