// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutboundPayload } from "./OutboundPayload";
import type { Protocol } from "./Protocol";

export type SendInfo = { id: string, name: string, addr: string, protocol: Protocol, ob: OutboundPayload, 
/**
 * The PIN a LocalSend receiver asked for. Quick Share has none.
 */
pin: string | null, };
