// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteDeviceInfo } from "./RemoteDeviceInfo";
import type { TextPayloadType } from "./TextPayloadType";
import type { WifiNetwork } from "./WifiNetwork";

export type TransferMetadata = { source: RemoteDeviceInfo | null, pin_code: string | null, destination: string | null, files: Array<string> | null, text_type: TextPayloadType | null, text_description: string | null, text_payload: string | null, wifi: WifiNetwork | null, total_bytes: number, ack_bytes: number, };
