// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WifiSecurity } from "./WifiSecurity";

export type WifiNetwork = { ssid: string, password: string, security: WifiSecurity, hidden: boolean, };
